scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.919862
    upper_angle: 1.919862
#~                                                                                                        
#~                             