#!/usr/bin/env python3

from visualization_msgs.msg import Marker
from geometry_msgs.msg import Point
from sensor_msgs.msg import PointCloud
import rospy

publisher_marker = rospy.Publisher('line_marker_topic', Marker, queue_size=2)

rospy.init_node('line_marker')

while not rospy.is_shutdown():

    marker = Marker()
    # marker_arr = MarkerArray()
    rospy.loginfo('[MARKER LINES] WAITING')

    pt_cloud = rospy.wait_for_message("line_end_pts", PointCloud)
    rospy.loginfo('[MARKER LINES] found line_parameters')
    marker.header.frame_id = "base_laser"
    marker.id = 0
    marker.header.stamp = rospy.Time.now()
    marker.type = marker.LINE_LIST
    marker.ns = "line_lists_ns"
    marker.action = marker.ADD
    marker.pose.orientation.w = 1.0
    
    marker.scale.x = 0.05 # line width
    # setting marker color
    marker.color.a = 1.0
    marker.color.g = 1.0
    print("pt_cloud.points:",pt_cloud.points[0])
    num_pts = len(pt_cloud.points)
    num_lines = num_pts/2
    rospy.loginfo('[MARKER LINES] number of lines published to marker are: %0.3f' % num_lines)
    for i in range(num_pts):
        p = Point()
        p.x = pt_cloud.points[i].x 
        p.y = pt_cloud.points[i].y 
        p.z = 0.
        marker.points.append(p)
    # marker_arr.markers.append(marker)
    # publisher_marker_arr.publish(marker_arr)
    publisher_marker.publish(marker)

    rospy.sleep(0.01)
